project/bot/urls.py
from django.contrib import admin
from django.urls import path

from bot.views import home, get_response

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', home,name = 'bot'),
    path('get-response/', get_response),
]

if settings.DEBUG == True:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/',user_views.signup, name='signup'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'users/logout.html'),name = 'logout'),
    path('blog/', include('blog.urls') ),
    path('', user_views.viewHome, name='blog-home'),
    path('confirmation/', user_views.confirmation, name='confirmation'),
    path('bot/',include('bot.urls')),
    url(r'^chat/', include('chat.urls')),
    path('store/', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/blog/models.py
from django.contrib.auth.models import User
from django.db import models
import datetime
from django.forms import ModelForm
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.conf import settings



class Role(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class Account(AbstractUser):
    # id          = models.AutoField(primary_key=True )
    roleid      = models.ForeignKey(Role, on_delete= models.CASCADE,blank=True,null = True)
    dob         = models.DateField(default=datetime.date.today)
    address     = models.TextField(max_length=150,null=True)
    confirm     = models.IntegerField(default = 0,null = True)
    randNum     =models.IntegerField(default=0, null=True)


class Book(models.Model):
    name        = models.CharField(max_length=150)
    Author      = models.CharField(max_length=100)
    Dop         = models.TextField(max_length=100)
    id          = models.IntegerField(primary_key=True)


class Posts(models.Model):
    id          = models.IntegerField(primary_key=True)
    title       = models.TextField(max_length=100)
    date        = models.DateTimeField(default=timezone.now)
    content     = models.TextField()
    name        = models.CharField(max_length=100)
    def __str__(self):
        return self.title


class PostForm(ModelForm):
    class Meta:
        model = Posts
        fields = ['content']


class Comment(models.Model):
    user = models.ForeignKey(Account, default=1, on_delete=models.CASCADE)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return str(self.content)

project/users/models.py
import datetime

from django.db import models
from django import forms
from blog.models import Account


class Category(models.Model):
    id          = models.AutoField(primary_key=True)
    name        = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class Book(models.Model):
    name        = models.CharField(max_length=150)
    author      = models.CharField(max_length=100)
    dop         = models.DateField(default=datetime.date.today)
    id          = models.IntegerField(primary_key=True)
    owner       = models.ForeignKey(Account,on_delete=models.CASCADE)
    sale        = models.IntegerField()
    ispn        = models.CharField(max_length=100)
    description = models.TextField(max_length=2000)
    price       = models.IntegerField()
    copies      = models.IntegerField(default=1)
    rate        = models.FloatField(default=0,null=True)
    cover       = models.ImageField(default = 'empty_cover.png',upload_to = 'book_pics', null = True)
    category    = models.ForeignKey(Category, on_delete = models.CASCADE, null = True)

    def __str__(self):
        return self.name

    def get_sale(self):
        return (self.price * (self.sale / 100))


class Profile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    ebooks = models.ManyToManyField(Book, blank = True , null = True)

    def __str__(self):
        return self.user.username


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = Account
        fields = ['username', 'email' ,'address']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class ConfirmationForm(forms.Form): #Note that it is not inheriting from forms.ModelForm
    username    = forms.CharField(max_length = 20)
    code        = forms.IntegerField()
    #All my attributes here

project/users/views.py
from django.shortcuts import render, redirect
from blog.forms import AccountCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate,login
from blog.models import Account
from .models import UserUpdateForm, ProfileUpdateForm, ConfirmationForm
import random
from django.core.mail import send_mail
from store.models import AccountBook
from users.models import Book
import collections

def signup(request):
    if request.method == 'POST':
        form = AccountCreationForm(request.POST)
        if form.is_valid():
            form.save()
            con = random.randint(1000, 9999)
            user=Account.objects.get(username=request.POST.get('username'))
            email = user.email
            name=user.username
            Account.objects.update(randNum= con)
            msg = 'Hello '+name+', here is your verification code ' + str(con)
            send_mail(
                'Confirmation',
                msg,
                'socialbookstorefcih@gmail.com',
                [email],
                fail_silently=False,
            )

            return redirect('confirmation')
    else:
        form = AccountCreationForm()
    return render(request, 'users/signup.html', {'form': form})


def confirmation(request):
    if request.method == 'POST':
        form = ConfirmationForm(request.POST)
        if form.is_valid():
            username    = form.cleaned_data.get('username')
            code        = form.cleaned_data.get('code')
            # return redirect('omer')

            try:
                user = Account.objects.get(username = username)
                if user.randNum == code:
                    Account.objects.update(confirm = 1)
                    return redirect('login')

                else:
                    return redirect('confirmation')

            except Exception:
                return redirect('omer')
        else:
            form = ConfirmationForm()
    else:
        form = ConfirmationForm()
    return render(request,'users/confirmation.html',{'form':form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)


def viewHome(request):
    if(request.user.username):
        tasteList=[]

        if AccountBook.objects.filter(Accountid=request.user).count():
            for inst in AccountBook.objects.all():
                if (request.user.username == inst.Accountid.username):
                    l = str(inst.bookid.category)
                    tasteList.append(l)
            counter = collections.Counter(tasteList)
            taste = counter.most_common()[0][0]
            request.session['taste']=taste
    return render(request,'blog/home.html')



def confirm(request):
    if request.method == 'POST':
        form = ConfirmationForm()
        if form.is_valid():
            username    = form.cleaned_data.get('username')
            code        = form.cleaned_data.get('code')
            try:
                user = Account.objects.get(username = username)
                if user.randNum == code:
                    Account.objects.update(confirm = 1)
                    return redirect('omer')

                else:
                    return redirect('confirmation')

            except Exception:
                return redirect('omer')
        else:
            form = ConfirmationForm()
    else:
        form = ConfirmationForm()
    return render(request,'users/confirmation.html',{'form':form})

project/users/templates/users/confirmation.html
<!DOCTYPE html>
<html>
<body>

<h1>confrimation</h1>
    <form action="{% url 'confirmation' %}" method="POST">
        {% csrf_token%}

    {{form.as_p}}
    <button type="submit">Submit</button>

    </form>

</body>
</html>

project/users/templates/users/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <!--<h2>Sign up</h2>-->
  <!--<form method="post">-->
    <!--{% csrf_token %}-->
    <!--{{ form|crispy }}-->
    <!--<button type="submit">Sign In</button>-->
  <!--</form>-->




    <div class="site-section bg-light" id="contact-section">

      <div class="container">

        <div class="row mb-5">
            <div class="col-12 text-center">
              <h3 class="section-sub-title"> Log In </h3>
              <h2 class="section-title mb-3"> Welcome </h2>


            </div>
          </div>

        <div class="row justify-content-center">

          <div class="col-md-7 mb-5">


            <form id = "login-form" method="post" action="#" class="p-5 bg-white">
              {% csrf_token %}

              <h2 class="h4 text-black mb-5">Form</h2>

              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="id_username" >User Name</label>
                  <input type="text" name="username"  required id="id_username" class="form-control rounded-0">
                </div>
              </div>


              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="id_password" >Password</label>
                  <input type="password" name="password" required id="id_password"  class="form-control rounded-0">
              </div>
              </div>


              <div class="col-md-12">
                  <input type="submit" value="Log In" class="btn btn-black rounded-0 py-3 px-4">
              </div>

              <div>
                <small> Don't Have an Account ?</small>
                <a class="pl-0 pr-3" href="{% url 'signup' %}" > Sign Up </a>
              </div>



            </form>
          </div>


          </div>

        </div>

      </div>

{% endblock %}

project/users/templates/users/logout.html
{% extends 'blog/home.html' %}

project/users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<head>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<style>
    body{
    font-family:sans-serif;
    color:#3c3939;
    background-color:#f1f1f1;
    font-weight: 400;
    font-size: 1rem;
    }
    .profile-card{
    width:600;
    margin:auto;
    margin-top:100px;
    background : #fff;
    box-shadow: 0 4px 10px 0 rgba(0,0,0,0.5);
    }
    .image-container{
    position:relative;
    }
    .info{
    color:#f16821;
    margin-right: 16px;
    margin-left : 16px;
    }
    .main-container{
    padding : 20px;
    }

    .title
    {
      text-align: center;
      text-transform:Capitalize;
    }
</style>
</head>

<body>

    <div class="profile-card">
        <div class="image-container">
            <img src="{{ user.profile.image.url }}" alt="x" width="100%" height="300px">
        </div>

        <div class="main-container">
            <p >
               <h2 class="title" > {{ user.username }}</h2>
            </p>

            <p><i class="fa fa-home info" aria-hidden="true"></i> Address: {{ user.address }}</p>
            <p><i class="fa fa-envelope info" aria-hidden="true"></i> Email : {{ user.email }}</p>
            <p><i class="fa fa-birthday-cake info" aria-hidden="true"></i> BirthDay: {{ user.dob }}</p>
            <p><i class="fa fa-briefcase info" aria-hidden="true"></i> Role : {{ user.roleid}}</p>
            <hr>
            <p><i class="fa fa-shopping-cart info"></i> Your Cart
                <Ul style="list-style: none" >
                    <li > <i class="fa fa-book info"> </i> First-book </li>
                    <li > <i class="fa fa-book info"> </i> Secound-book </li>
                    <li > <i class="fa fa-book info"> </i> Third-book </li>
                </Ul>
            </p>

        </div>

        <form style="margin:16px;padding:50px;" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4"> Update Profile </legend>
              {{ u_form|crispy }}
              {{ p_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button style="color:f16821" class="btn" type="submit">Update</button>
          </div>
      </form>
    </div>

</body>
{% endblock content %}

project/users/templates/users/readerForm.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

project/users/templates/users/signup.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <!--<h2>Sign up</h2>-->
  <!--<form method="post">-->
    <!--{% csrf_token %}-->
    <!--{{ form|crispy }} -->
    <!--<button type="submit">Sign up</button>-->
  <!--</form>-->




    <div class="site-section bg-light" id="contact-section">

      <div class="container">

        <div class="row mb-5">
            <div class="col-12 text-center">
              <h3 class="section-sub-title"> Sign Up </h3>
              <h2 class="section-title mb-3">Join Us !</h2>
            </div>
          </div>

        <div class="row justify-content-center">

          <div class="col-md-7 mb-5">


            <form method="post" action="#" class="p-5 bg-white">
              {% csrf_token %}
<!--              fields = ['name', 'username', 'email','roleid','password','phone','dob','address','profilepic'] -->
              <h2 class="h4 text-black mb-5">Form</h2>

<!--              <div class="row form-group">-->
<!--                <div class="col-md-6 mb-3 mb-md-0">-->
<!--                  <label class="text-black" for="id_name" >First Name</label>-->
<!--                  <input type="text" name="name"  required id="id_name" class="form-control rounded-0">-->
<!--                </div>-->
<!--              </div>-->

              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="id_username" >User Name</label>
                  <input type="text" name="username" required id="id_username" class="form-control rounded-0">
                </div>
              </div>


              <div class="row form-group">

                <div class="col-md-12">
                  <label class="text-black" for="id_email" >Email</label>
                  <input type="email" name="email" required id="id_email" class="form-control rounded-0">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="id_password1" >Password</label>
                  <input type="password" name="password1" required id="id_password1"  class="form-control rounded-0">
              </div>
              </div>
              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="id_password2" >Confirm Password</label>
                  <input type="password" name="password2" required id="id_password2"  class="form-control rounded-0">
              </div>
              </div>

<!--              <div class="row form-group">-->
<!--                <div class="col-md-6 mb-3 mb-md-0">-->
<!--                  <label class="text-black" for="id_phone" >Phone Number</label>-->
<!--                  <input type="number" name="phone" required id="id_phone"  class="form-control rounded-0">-->
<!--              </div>-->
<!--              </div>-->

              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="id_dob" >Date of Birth</label>
                  <input type="date" name="dob" required id="id_dob"  class="form-control rounded-0">
              </div>
              </div>

               <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="id_address" >Address</label>
                  <input type="text" name="address" required id="id_address"  class="form-control rounded-0">
              </div>
              </div>


              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">

                   <label>Select Type</label>
                   <select  name="roleid" required id = "id_roleid">
                     {% for role in form.roleid %}
                     <option>{{role}}</option>
                     {%endfor%}
                   </select>

              </div>
              </div>


              <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" value="Sign Up" class="btn btn-black rounded-0 py-3 px-4">
                </div>
              </div>

                <div>
                <small> Already Have an Account ?</small>
                <a class="pl-0 pr-3" href="{% url 'login' %}" > Log In </a>
              </div>

              <!--This Code Is For View Invalid Fields-->
              {% if form.errors %}
                  {% for field in form %}
                      {% for error in field.errors %}
                          <div class="alert alert-danger">
                              <strong>{{ error|escape }}</strong>
                          </div>
                      {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                      <div class="alert alert-danger">
                          <strong>{{ error|escape }}</strong>
                      </div>
                  {% endfor %}
              {% endif %}
            </form>

          </div>

        </div>

      </div>
    </div>
{% endblock %}

project/users/templates/users/test.html
{% extends 'blog/base.html' %}


{% load static %}
{% block content %}
<link  href="{% static 'users/signup.css' %}" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container register">
                <div class="row">
                    <div class="col-md-3 register-left">
                        <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
                        <h3>Welcome</h3>
                        <p>You are 30 seconds away from earning your own money!</p>
                        <input type="submit" name="" value="Login"/><br/>
                    </div>
                    <div class="col-md-9 register-right">
                        <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Employee</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Hirer</a>
                            </li>
                        </ul>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <h3 class="register-heading">Apply as a Employee</h3>
                                <div class="row register-form">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Name" value="">{{ form.name }}</input>
                                        </div>
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="User Name" value="" >{{ form.username }}</input>
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control" placeholder="Password" value="" >{{ form.password }}</input>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="email" class="form-control" placeholder="Your Email" value="" >{{ form.email }}</input>
                                        </div>
                                        <div class="form-group">
                                            <input type="text" minlength="10" maxlength="10" name="txtEmpPhone" class="form-control" placeholder="Your Phone" value="" >{{ form.phone }}</input>
                                        </div>

                                        <input type="submit" class="btnRegister"  value="Register"/>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                <h3  class="register-heading">Apply as a Hirer</h3>
                                <div class="row register-form">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="First Name *" value="" />
                                        </div>
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Last Name *" value="" />
                                        </div>
                                        <div class="form-group">
                                            <input type="email" class="form-control" placeholder="Email *" value="" />
                                        </div>
                                        <div class="form-group">
                                            <input type="text" maxlength="10" minlength="10" class="form-control" placeholder="Phone *" value="" />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="password" class="form-control" placeholder="Password *" value="" />
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control" placeholder="Confirm Password *" value="" />
                                        </div>
                                        <div class="form-group">
                                            <select class="form-control">
                                                <option class="hidden"  selected disabled>Please select your Sequrity Question</option>
                                                <option>What is your Birthdate?</option>
                                                <option>What is Your old Phone Number</option>
                                                <option>What is your Pet Name?</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="`Answer *" value="" />
                                        </div>
                                        <input type="submit" class="btnRegister"  value="Register"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
{% endblock %}

project/users/templates/users/writerForm.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}