project/bot/urls.py
from django.contrib import admin
from django.urls import path

from bot.views import home, get_response

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', home,name = 'bot'),
    path('get-response/', get_response),
]

if settings.DEBUG == True:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/',user_views.signup, name='signup'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'users/logout.html'),name = 'logout'),
    path('blog/', include('blog.urls') ),
    path('', user_views.viewHome, name='blog-home'),
    path('confirmation/', user_views.confirmation, name='confirmation'),
    path('bot/',include('bot.urls')),
    url(r'^chat/', include('chat.urls')),
    path('store/', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/store/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import AddBook,book_profile,addToLikes,ViewLikes,Search,search_bassem
from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success,
    book_list,process_payment,transactions)
app_name = "store"

urlpatterns = [
    path('new/', AddBook.as_view(), name='add-book'),
    path('shop/',book_list, name='book'),
    path('book_profile/<int:pk>/',book_profile.as_view(),name='book_profile'),
    path('addtolikes/<book>/',addToLikes,name='addToLikes' ),
    path('likes/', ViewLikes.as_view(), name='view-likes'),
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^transactions/$', transactions, name='transactions'),
    url(r'^update-transaction/(?P<order_id>[-\w]+)/$', update_transaction_records, name='update_records'),
    url(r'^payment/(?P<order_id>[-\w]+)/$', process_payment, name='process_payment'),
    path('search/',search_bassem,name='search'),
    path('searchh/',Search.as_view(),name='search2'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/blog/models.py
from django.contrib.auth.models import User
from django.db import models
import datetime
from django.forms import ModelForm
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.conf import settings



class Role(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class Account(AbstractUser):
    # id          = models.AutoField(primary_key=True )
    roleid      = models.ForeignKey(Role, on_delete= models.CASCADE,blank=True,null = True)
    dob         = models.DateField(default=datetime.date.today)
    address     = models.TextField(max_length=150,null=True)
    confirm     = models.IntegerField(default = 0,null = True)
    randNum     =models.IntegerField(default=0, null=True)


class Book(models.Model):
    name        = models.CharField(max_length=150)
    Author      = models.CharField(max_length=100)
    Dop         = models.TextField(max_length=100)
    id          = models.IntegerField(primary_key=True)


class Posts(models.Model):
    id          = models.IntegerField(primary_key=True)
    title       = models.TextField(max_length=100)
    date        = models.DateTimeField(default=timezone.now)
    content     = models.TextField()
    name        = models.CharField(max_length=100)
    def __str__(self):
        return self.title


class PostForm(ModelForm):
    class Meta:
        model = Posts
        fields = ['content']


class Comment(models.Model):
    user = models.ForeignKey(Account, default=1, on_delete=models.CASCADE)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return str(self.content)

project/store/models.py
from django.db import models
from django import forms
from PIL import Image


# Create your models here.
import datetime
from blog.models import Account
from users.models import Profile, Book


class OrderItem(models.Model):
    product = models.ForeignKey(Book, on_delete = models.CASCADE, null = True)
    is_ordered = models.BooleanField(default = True, null = True)
    date_ordered = models.DateTimeField(null = True)
    date_added = models.DateTimeField(auto_now = True, null = True)
    amount = models.IntegerField(default = 1, null = True)

    def __str__(self):
        return self.product.name


class Order(models.Model):
    id              = models.AutoField(primary_key=True)
    ref_code        = models.CharField(max_length = 15, null = True)
    date_ordered    = models.DateTimeField(auto_now = True, null = True)
    is_ordered       = models.BooleanField(default = False, null = True)
    items           = models.ManyToManyField(OrderItem)
    owner           = models.ForeignKey(Profile,on_delete = models.CASCADE, null = True)

    def get_cart_items(self):
        return self.items.all()
    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        return '{0}-{1}'.format(self.owner, self.ref_code)


class Book_Profile(models.Model):
    book        = models.OneToOneField(Book,on_delete=models.CASCADE)
    image       = models.ImageField(default='default.jpg', upload_to='book_pics')
    # def save(self):
    #     super(Book_Profile, self).save()
    #     img = Image.open(self.image.path)
    #
    #     if img.height > 300 or img.width > 300:
    #         output_size = (500,300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)

class AccountBook(models.Model):
    bookid      = models.ForeignKey(Book , on_delete= models.CASCADE)
    Accountid   = models.ForeignKey(Account , on_delete=models.CASCADE)

class SearchForm(forms.Form):
    search_content  = forms.CharField(max_length=20)

project/users/models.py
import datetime

from django.db import models
from django import forms
from blog.models import Account


class Category(models.Model):
    id          = models.AutoField(primary_key=True)
    name        = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class Book(models.Model):
    name        = models.CharField(max_length=150)
    author      = models.CharField(max_length=100)
    dop         = models.DateField(default=datetime.date.today)
    id          = models.IntegerField(primary_key=True)
    owner       = models.ForeignKey(Account,on_delete=models.CASCADE)
    sale        = models.IntegerField()
    ispn        = models.CharField(max_length=100)
    description = models.TextField(max_length=2000)
    price       = models.IntegerField()
    copies      = models.IntegerField(default=1)
    rate        = models.FloatField(default=0,null=True)
    cover       = models.ImageField(default = 'empty_cover.png',upload_to = 'book_pics', null = True)
    category    = models.ForeignKey(Category, on_delete = models.CASCADE, null = True)

    def __str__(self):
        return self.name

    def get_sale(self):
        return (self.price * (self.sale / 100))


class Profile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    ebooks = models.ManyToManyField(Book, blank = True , null = True)

    def __str__(self):
        return self.user.username


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = Account
        fields = ['username', 'email' ,'address']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class ConfirmationForm(forms.Form): #Note that it is not inheriting from forms.ModelForm
    username    = forms.CharField(max_length = 20)
    code        = forms.IntegerField()
    #All my attributes here

project/store/views.py
import datetime

from django.shortcuts import render,get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView
from store.extras import generate_order_id
from .models import SearchForm
from store.models import Book, Order, OrderItem
from users.models import Profile
from .models import AccountBook
from blog.models import Account, Posts, Comment
from django.contrib.auth.decorators import login_required
from django.contrib import messages

class AddBook(CreateView):
    model = Book
    template_name = 'store/store.html'
    fields = ['name', 'author', 'dop', 'sale','ispn','description','price','copies','cover','category']

    # This Line Is For Redirect To Home After Adding A New Post
    success_url = reverse_lazy('blog-home')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ViewBook(ListView):
    model=Book
    template_name='store/shop.html'
    context_object_name='books'

class ViewLikes(ListView):
    model=AccountBook
    template_name='store/likes.html'
    context_object_name='Accountbooks'

class book_profile(DetailView):
    model = Book
    template_name = "store/book_profile.html"

def addToLikes(request,book):
    book_id = Book.objects.get(id = book)
    user = Account.objects.get(username = request.user.username)
    AccountBook.objects.create(bookid=book_id,Accountid=user)
    return redirect('blog-home')


@login_required()
def book_list(request):
    object_list = Book.objects.filter(copies__gt=0)
    filtered_orders = Order.objects.filter(owner = request.user.profile, is_ordered=False)
    current_order_products = []
    if filtered_orders.exists():
        user_order = filtered_orders[0]
        user_order_items = user_order.items.all()
        current_order_products = [product.product for product in user_order_items]

    context = {
        'object_list': object_list,
        'current_order_products': current_order_products
    }

    return render(request, "store/shop.html", context)


@login_required()
def get_user_pending_order(request):
    user_profile = get_object_or_404(Profile ,user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        return order[0]
    return 0


@login_required()
def add_to_cart(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # filter products by id
    product = Book.objects.filter(id=kwargs.get('item_id', "")).first()
    # check if the user already owns this product
    if product in request.user.profile.ebooks.all():
        messages.info(request, 'You already own this ebook')
        return redirect(reverse('store:book'))
    # create orderItem of the selected product
    order_item, status = OrderItem.objects.get_or_create(product=product)
    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()

    # show confirmation message and redirect back to the same page
    messages.info(request, "item added to cart")
    return redirect(reverse('store:book'))


@login_required()
def delete_from_cart(request,item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request,"Item has been deleted")
    return redirect(reverse('store:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request,'store/order_summary.html',context)


@login_required()
def checkout(request):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order,
    }
    return render(request, 'store/checkout.html', context)



@login_required()
def process_payment(request , order_id):
    order = Order.objects.get(id=order_id)
    for item in order.items.all():
        book = Book.objects.get(name=item.product.name)
        book_copies = book.copies - item.amount
        Book.objects.filter(name=item.product.name).update(copies=book_copies)

    return redirect(reverse('store:update_records',kwargs ={
        'order_id':order_id})
                    )


@login_required()
def update_transaction_records(request, order_id):
    order_to_purchase = Order.objects.filter(pk=order_id).first()
    order_to_purchase.is_ordered = True
    order_to_purchase.date_order = datetime.datetime.now()
    order_to_purchase.save()

    order_items = order_to_purchase.items.all()
    order_items.update(is_ordered = True, date_ordered = datetime.datetime.now())
    user_profile = get_object_or_404(Profile,user=request.user)

    order_products = [item.product for item in order_items]

    user_profile.ebooks.add(*order_products)

    user_profile.save()
    messages.info(request, " Thank you! Your Items have been added to your profile")
    return redirect(reverse('store:book'))


def success(request, **kwargs):
    return render(request, 'store/purchase_success.html',{})

def search_bassem(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            request.session['search_content'] = request.POST['search_content']
            return redirect('store:search2')
    return render(request, 'store/search.html',{})




def transactions(request):
    profile = Profile.objects.all()
    request.session['username'] = request.user.username
    return render(request,"store/transactions.html",{'profiles':profile})


class Search(ListView):
    model = Book
    template_name = 'store/search2.html'
    context_object_name = 'Book'
    # success_url = reverse_lazy('searchh')

project/store/templates/store/book_profile.html
{% extends "blog/base.html" %}
{% block content %}

<div class="site-section bg-light">
      <div class="container">
        <div class="row mb-5 justify-content-center">
          <div class="col-md-6 text-center">

            <h2 class="section-title mb-3">{{object.name}}</h2>
          </div>
        </div>
        <div class="bg-white py-4 mb-4">
          <div class="row mx-4 my-4 product-item-2 align-items-start">
            <div class="col-md-6 mb-5 mb-md-0">
              <img style="height:550px;width:400px;" src="{{ object.cover.url }}" alt="Image" class="img-fluid">
            </div>

            <div  class="col-md-5 ml-auto product-title-wrap">

              <h3 class="text-black mb-4 font-weight-bold">More About {{object.name}}</h3>
              <p class="mb-4">{{ object.description }}</p>

              <div class="mb-4">
                <h3 class="text-black font-weight-bold h5">Price :</h3>
                <div class="price">{{object.price}}</div>
              </div>

              <div class="mb-4">
                <h3 class="text-black font-weight-bold h5">Author :</h3>
                <div class="price">{{object.author}}</div>
              </div>


              <p>
                <a href="#" class="btn btn-black rounded-0 d-block d-lg-inline-block">Cart</a>
                <a href="{% url 'store:addToLikes' object.id %}" class="btn btn-black btn-outline-black rounded-0 d-block mb-2 mb-lg-0 d-lg-inline-block">Like</a>
              </p>
            </div>
          </div>
        </div>


      </div>
    </div>
{% endblock%}

project/store/templates/store/checkout.html
{%extends 'blog/base.html'%}
{%block content%}
    <style>
      table.borderless td,table.borderless th{
        border: none !important;
      }
    </style>

    <section>
      <div class="row" id="table row">
      <div class="col-md-4 col-xs-12">
        <div class="panel panel-primary">
          <div class="panel-body">
            <h5>Enter Voucher Code Below<br><small>If multiple, separate each with comma</small></h5>

            <div>
              <form action="." method="post">
                {% csrf_token %}
                <input type="text"  name="voucher_codes" class="form-control" id="voucher_code" required>
                <input type="hidden"  name="order_id" value="{{ order.id }}">
                <br>
                <span>
                  <input type="submit" class="btn btn-warning pull-right" value="Apply Voucher">
                </span>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8 col-xs-12">
        <table class="table">
          <tr>
            <td><h4>Order Summary</h4></td>
          </tr>
          <tr>
            <td>
              {% for item in order.get_cart_items %}
                <tr>
                  <td>{{ item }}</td>
                  <td>${{ item.product.price }}</td>
                </tr>
              {% endfor %}
            </td>
          </tr>
          <tr>
            <td><strong>Order Total</strong> </td>
            <td> <strong>${{ order.get_cart_total }}</strong></td>
          </tr>
        </table>
         <form method="POST" action="{% url 'store:process_payment' order.id%}">
          {% csrf_token%}
          <button style="width: 50%; float: left;" class="btn btn-primary"> Pay With Card</button>
        </form>
        <form method="POST" action="{% url 'store:process_payment' order.id%}">
          {% csrf_token%}
          <button style="width: 50%; float: right;" class="btn btn-primary"> Pay With Paypal</button>
        </form>
      </div>
     </div>
    </section>
{%endblock content%}


project/store/templates/store/messages.html
{% if messages %}
 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

project/store/templates/store/order_summary.html
{% extends "blog/base.html" %}
{% block content %}

 <section>
   <div class="row">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>no.</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.product.name }}
             <span class="pull-right">
              <a href="{% url 'store:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fas fa-trash"></i>
              </a>
            </span>
          </td>
          <td>{{ item.product.price }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=2>
          <strong class="pull-right">Order Total:</strong>
        </td>
        
        <td colspan= 1>
          $<strong>{{ order.get_cart_total }}</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="{% url 'store:book' %}" class="btn btn-warning pull-left">
            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a> 
        </td>
        <td colspan=2>
          {% if order.get_cart_items %}
            <a href="{% url 'store:checkout' %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
          {% endif %}
        </td>
      </tr>
    </table>
     
   </div>
 </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %}

project/store/templates/store/search.html
{% extends "blog/base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Search</title>
</head>
<body>
<br/>
<br/>
<br/>
<br/>
<br/>
<form action="{% url 'store:search' %}" method="post">
    {%csrf_token%}

    <input name="search_content" required id="id_search_content" type="text" size="100"/><br/>
    <input id="search-submit" type="submit" value="Enter"/>
</form>
</body>
</html>
{%endblock content%}

project/store/templates/store/shop.html
{% extends "blog/base.html" %}
{% block content %}
{% load static %}
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" href="{% static 'blog/swiper.min.css' %}">
  <style>
  .swiper-container {
      width: 100%;
      padding:auto;
      position: relative;
      height: 390px;

    }
    .swiper-slide {
      text-align: center;
      font-size: 18px;
      background: #fff;
      height:380px;
      /* Center slide text vertically */
      display: -webkit-box;
      display: -ms-flexbox;
      display: -webkit-flex;
      display: flex;
      -webkit-box-pack: center;
      -ms-flex-pack: center;
      -webkit-justify-content: center;
      justify-content: center;
      -webkit-box-align: center;
      -ms-flex-align: center;
      -webkit-align-items: center;
      align-items: center;

    }
  </style>
</head>

<body>
<script type="text/javascript" src="{% static 'blog/swiper.min.js' %}"></script>

    <div class="site-section" id="products-section">
      <div class="container">
        <div class="row mb-5 justify-content-center">
          <div class="col-md-6 text-center">
            <h3 class="section-sub-title">Book Store</h3>
            <h2 class="section-title mb-3">Our Products</h2>
            <p>Here's variety of book categories and unique packages that appeal to different customers’ preferences , We manage to serve different tastes of readers and to give them personalized service</p>
            <p>Some Recommendations specially for you</p>
          </div>



                  <div class="swiper-container" >
                  <div class="swiper-wrapper">
                    {%for object in object_list %}
                    {% if object.category.name == request.session.taste %}
                    <div class="swiper-slide" style="height:100%;" >
                    <div class="imgbox"  >
                    <img style="height:300px;" src="{{ object.cover.url }}">
                    <div class="detail"  >
                    <h5>{{object.name}}<br><span>{{object.author}}</span></h5>
                    </div>
                    </div>
                    </div>
                    {%endif%}
                    {%endfor%}

                  </div>
                  <!-- Add Pagination -->
                  <div class="swiper-pagination"></div>
                  <!-- Add Arrows -->
                  <div class="swiper-button-next"></div>
                  <div class="swiper-button-prev"></div>
                  </div>



</div>
        <hr>
<div class="row">


{% for object in object_list%}
          <div class="col-lg-4 col-md-6 mb-5">
            <div class="product-item">
              <figure >
                <img style="width:300;height:300;padding:auto;" src="{{ object.cover.url }}" alt="Image" class="img-fluid">
              </figure>
              <div class="px-4">
                <h3><a href="#">{{object.name}}</a></h3>
                <!--<div class="mb-3">-->
                  <!--<span class="meta-icons mr-3"><a href="#" class="mr-2"><span class="icon-star text-warning"></span></a> 5.0</span>-->
                  <!--<span class="meta-icons wishlist"><a href="#" class="mr-2"><span class="icon-heart"></span></a> 29</span>-->
                <!--</div>-->
                <p class="mb-4"><small>Book Author : </small>{{object.author}}</p>
                {% if object.sale == 0.0%}
                <p class="mb-4" ><small>Book Price : </small>{{object.price}}</p>
                  {%else%}
                <div class="mb-4">
                  <p  style="text-decoration:line-through" ><small>Book Price : </small>{{object.price}}</p>
                <p ><strong>New Price : </strong>{{object.get_sale}}</p>
                </div>
                    {%endif%}
                 <div>

		{% if object in user.profile.ebooks.all %}
	            <!-- add a button here to see the product -->
		            You own this
                  {% elif object in current_order_products %}
                    <a href="{% url 'store:order_summary' %}" class="btn btn-black btn-outline-black ml-1 rounded-0">Go to Cart</a>
                  {% else %}
                    <a href="{% url 'store:add_to_cart' object.id%}" class="btn btn-black btn-outline-black ml-1 rounded-0">Add to Cart</a>
                  {% endif %}
                  <a href="{% url 'store:book_profile' object.id%}" class="btn btn-black btn-outline-black ml-1 rounded-0">View</a>
                  <a href="{% url 'store:addToLikes' object.id %}" class="btn btn-black btn-outline-black ml-1 rounded-0">Add to like</a>

                </div>
              </div>
            </div>
          </div>
{%endfor%}

          </div>
      </div>
    </div>
<script>
    var swiper = new Swiper('.swiper-container', {
      spaceBetween: 30,
      centeredSlides: true,
      autoplay: {
        delay: 2500,
        disableOnInteraction: false,
      },
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
  </script>
</body>
</html>
{%endblock%}

project/store/templates/store/store.html
{% extends "blog/base.html" %}
{%block content%}
<!------ Include the above in your HEAD tag ---------->

<section class="testimonial py-5" id="testimonial">
    <div class="container">
        <div class="row ">
            <div class="col-md-4 py-5 bg-primary text-white text-center ">
                <div class=" ">
                    <div class="card-body">
                        <img src="../../static/store/reading.svg" style="width:50%">
                        <h2 class="py-3">Book</h2>
                        <p>Here You Can Add Any Type Of Book You Want To Be Added To Our Book Shop</p>
                    </div>
                </div>
            </div>
            <div class="col-md-8 py-5 border">
                <h4 class="pb-4">Please fill with your details</h4>
<!--                    fields = ['name', 'author', 'dop', 'sale', 'cover', 'ispn', 'category', 'description']-->

                <form method="post" enctype="multipart/form-data">
                    {%csrf_token%}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                          <input id="id_name" name="name" placeholder="Book Name" class="form-control" type="text">
                        </div>
                        <div class="form-group col-md-6">
                          <input type="text" class="form-control" id="id_author" name="author" placeholder="Author Name">
                        </div>
                      </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                          <input id="id_ispn" name="ispn" placeholder="ISPN CODE" class="form-control" type="number">
                        </div>
                        <div class="form-group col-md-6">
                          <input type="date" class="form-control" id="id_dop"  name = "dop" placeholder="Date Of Publish">
                        </div>
                      </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                          <input id="id_sale" name="sale" placeholder="Sale Percentage" class="form-control" type="number">
                        </div>
 <div class="form-group col-md-6">
                          <select  name="category" required id = "id_category">
                        {% for category in form.category %}
                        <option>{{category}}</option>
                        {%endfor%}
                        </select>
                        </div>
                      </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                          <input type="number" class="form-control" id="id_price" name="price" placeholder="Price">
                        </div>
                        <div class="form-group col-md-6">
                          <input type="number" class="form-control" id="id_copies" name="copies" placeholder="No. Copies">
                        </div>


                        <div class="form-group col-md-12">
                          <input type="file" class="form-control" id="id_cover" name="cover" placeholder="Book Cover">
                        </div>
                        <div class="form-group col-md-12">
                            <textarea id="id_description" name="description" cols="40" rows="5" class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="form-row col-md-6">
                        <button type="submit" class="btn btn-danger">Add</button>
                    </div>
                    {% if form.errors %}
                  {% for field in form %}
                      {% for error in field.errors %}
                          <div class="alert alert-danger">
                              <strong>{{ field.name }}</strong>
                          </div>
                      {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                      <div class="alert alert-danger">
                          <strong>{{ field.name }}</strong>
                      </div>
                  {% endfor %}
              {% endif %}
                </form>
            </div>
        </div>
    </div>
</section>
{%endblock%}