project/blog/urls.py
from django.urls import path
from . import views
from .views import PostListView, PostCreateView
urlpatterns = [
    path( 'about/', views.about , name='blog-about' ),
    path('view/', PostListView.as_view(), name='view-posts'),
    path('new/', PostCreateView.as_view(), name='create-post'),

]

project/bot/urls.py
from django.contrib import admin
from django.urls import path

from bot.views import home, get_response

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', home,name = 'bot'),
    path('get-response/', get_response),
]

if settings.DEBUG == True:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/',user_views.signup, name='signup'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'users/logout.html'),name = 'logout'),
    path('blog/', include('blog.urls') ),
    path('', user_views.viewHome, name='blog-home'),
    path('confirmation/', user_views.confirmation, name='confirmation'),
    path('bot/',include('bot.urls')),
    url(r'^chat/', include('chat.urls')),
    path('store/', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/store/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import AddBook,book_profile,addToLikes,ViewLikes,Search,search_bassem
from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success,
    book_list,process_payment,transactions)
app_name = "store"

urlpatterns = [
    path('new/', AddBook.as_view(), name='add-book'),
    path('shop/',book_list, name='book'),
    path('book_profile/<int:pk>/',book_profile.as_view(),name='book_profile'),
    path('addtolikes/<book>/',addToLikes,name='addToLikes' ),
    path('likes/', ViewLikes.as_view(), name='view-likes'),
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^transactions/$', transactions, name='transactions'),
    url(r'^update-transaction/(?P<order_id>[-\w]+)/$', update_transaction_records, name='update_records'),
    url(r'^payment/(?P<order_id>[-\w]+)/$', process_payment, name='process_payment'),
    path('search/',search_bassem,name='search'),
    path('searchh/',Search.as_view(),name='search2'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/blog/models.py
from django.contrib.auth.models import User
from django.db import models
import datetime
from django.forms import ModelForm
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.conf import settings



class Role(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class Account(AbstractUser):
    # id          = models.AutoField(primary_key=True )
    roleid      = models.ForeignKey(Role, on_delete= models.CASCADE,blank=True,null = True)
    dob         = models.DateField(default=datetime.date.today)
    address     = models.TextField(max_length=150,null=True)
    confirm     = models.IntegerField(default = 0,null = True)
    randNum     =models.IntegerField(default=0, null=True)


class Book(models.Model):
    name        = models.CharField(max_length=150)
    Author      = models.CharField(max_length=100)
    Dop         = models.TextField(max_length=100)
    id          = models.IntegerField(primary_key=True)


class Posts(models.Model):
    id          = models.IntegerField(primary_key=True)
    title       = models.TextField(max_length=100)
    date        = models.DateTimeField(default=timezone.now)
    content     = models.TextField()
    name        = models.CharField(max_length=100)
    def __str__(self):
        return self.title


class PostForm(ModelForm):
    class Meta:
        model = Posts
        fields = ['content']


class Comment(models.Model):
    user = models.ForeignKey(Account, default=1, on_delete=models.CASCADE)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return str(self.content)

project/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Account,Comment


class AccountCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = Account
        fields = ( 'username', 'email','roleid','password1','password2','dob','address')

class AccountChangeForm(UserChangeForm):

    class Meta:
        model = Account
        fields = ('username', 'email')

project/blog/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from blog.models import Account, Comment
from blog.models import Role
from django.views.generic import ListView, CreateView
from .models import Posts
from blog.models import PostForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse


def post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog-home')
    else:
        form = PostForm()
    #return render(request, 'users/signup.html', {'form': form})


def home(request):
    context = {
        'posts' : Role.objects.all(),'accounts': Account.objects.all()
    }
    return render(request,'blog/home.html', context)


class PostListView(ListView):
    model=Posts
    template_name='blog/blogPosts.html'
    context_object_name='posts'
    ordering =['-date']


class PostCreateView(CreateView):
    model = Posts
    template_name = 'blog/post_form.html'
    fields = ['title', 'content']

    #This Line Is For Redirect To Home After Adding A New Post
    success_url = reverse_lazy('blog-home')
    def form_valid(self,form):
        form.instance.name = self.request.user
        return super().form_valid(form)


def about(request):
    return render(request,'blog/about.html' , {'title': 'About'} )

project/blog/templates/blog/about.html
{% extends "blog/base.html"%}

#CONTENT

    {% block content %}
    <h1>About Blog!</h1>
    {%endblock content%}

project/blog/templates/blog/base.html
{% load static %}
<html>
<head lang="en">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/fontstyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/jqueryui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/themedefault.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/datapicker.css' %}">
<link rel= 'stylesheet' type="text/css" href="{% static 'chatbot/css/bot.css' %}">
<!--    <link rel="stylesheet" type="text/css" href="{% static 'blog/aos.css' %}">-->
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
<!--    <link rel="stylesheet" type="text/css" href="{% static 'blog/flaticon.css' %}">-->

    {% if title %}
        <title>{{ title }}</title>

    {% else %}
        <title>ReadersHUB</title>

    {% endif %}
</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300" >
    <div class="site-wrap">

        <header class="site-navbar py-4 bg-white js-sticky-header site-navbar-target" role="banner" style="top:0px;">
            <div class="container">
            <div class="row align-items-center">
            <div class="col-6 col-xl-2">
            <h1 class="mb-0 site-logo"><a href="{% url 'blog-home' %}" class="text-black mb-0">ReadersHUB<span class="text-primary">.</span> </a></h1>
            </div>
            <div class="col-12 col-md-10 d-none d-xl-block">
                <nav class="site-navigation position-relative text-right" role="navigation">
                    <ul   class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                        <li><a href="{% url 'blog-home' %}" class="nav-link">Home</a></li>
                        {% if user.is_authenticated and user.confirm ==  1 %}
                       <a  href="{% url 'index' %}">Chat!</a>

                        <li ><a href="{% url 'store:view-likes' %}" class="nav-link">My Likes</a></li>


                        <li style="color:#000 ;"><ul>
        <a style="left:70%" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">Profile</a>
        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
              <a style="color:#B22222	" class="dropdown-item" href="{% url 'profile' %}">
                        {{user.username}}</a>
    <a  style="color:#B22222	" class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
      </li>

    </ul>

</li>

                        <a href="{% url 'view-posts' %}">view Posts</a>


                        {% if user.roleid.id  == 2  %}
                         <a href="{% url 'create-post' %}">Add Post</a>
                        {% elif user.roleid.id  == 3 %}
                        <a href="{% url 'store:add-book' %}">Add Book</a>
                        <a href="{% url 'store:transactions' %}">View Orders</a>
                        {% endif %}
                    {% else %}
                        <li><a href="{% url 'signup' %}" class="nav-link">Register</a></li>
                        <li><a href="{% url 'login' %}" class="nav-link">Login</a></li>
                    {% endif %}

                    </ul>
                </nav>
            </div>
            <div class="col-6 d-inline-block d-xl-none ml-md-0 py-3" style="position: relative; top: 3px;"><a href="#" class="site-menu-toggle js-menu-toggle text-black float-right"><span class="icon-menu h3"></span></a></div>
            </div>
            </div>
        </header>
        <div>
        {% block content %}
        {% endblock %}
        </div>

           <footer class="site-footer bg-white ">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <div class="row">
              <div class="col-md-5">
                <h2 class="footer-heading mb-4">About Us</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque facere laudantium magnam voluptatum autem. Amet aliquid nesciunt veritatis aliquam.</p>
              </div>
              <div class="col-md-3 ">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Services</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>

            </div>
          </div>

        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="border-top pt-5">
            <p>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made by BookStore
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      </p>
            </div>
          </div>

        </div>
      </div>
    </footer>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %} "></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <script src="{% static '/chatbot/js/script.js' %}"></script>
    <script src="{% static '/chatbot/js/dev-vue.js' %}"></script>


    </div>
    </body>
</html>

project/blog/templates/blog/blogPosts.html
{% extends "blog/base.html" %}
{% block content %}-

<div class="site-section bg-light">
      <div class="container">
            <div class="row mb-5 justify-content-center">
              <div class="col-md-6 text-center">
                <h3 class="section-sub-title">Get in touch with your writers</h3>
                <h2 class="section-title mb-3">Authors Posts</h2>
                <p>A huge number of writers and their daily posts</p>
              </div>
            </div>
          {% for post in posts %}
            <div class="bg-white py-4 mb-4">
              <div class="row mx-4 my-4 product-item-2 align-items-start">
                <div class="col-md-6 mb-5 mb-md-0">
                  <img style="width:300px;height:300px" src="{{ post.name.profile.image.url }}" alt="Image" class="img-fluid">
                </div>

                <div class="col-md-5 ml-auto product-title-wrap">
                  <span class="number"></span>
                  <h3 class="text-black mb-4 font-weight-bold">{{ post.title }}</h3>
                  <p class="mb-4">{{ post.content }}</p>


                  <div class="mb-4">
                    <h3 class="text-black font-weight-bold h5"><small>Written by : </small>{{ post.name }}</h3>
                    <div class="price"><small>Posted on  : </small>{{ post.date }}</div>
                  </div>
                  <p>
                    <!--<a href="#" class="btn btn-black btn-outline-black rounded-0 d-block mb-2 mb-lg-0 d-lg-inline-block">View Details</a>-->
                    <a href="#" class="btn btn-black rounded-0 d-block d-lg-inline-block">Add Comment</a>
                  </p>
                </div>
              </div>
            </div>
          {% endfor %}

      </div>
</div>
{% endblock content %}

project/blog/templates/blog/home.html
{% extends "blog/base.html"%}
{% load static %}

#CONTENT

    {% block content %}
        <div class="site-blocks-cover overlay" style="background-image : url({% static 'blog\images\home.jpg' %});" data-aos="fade" data-stellar-background-ratio="0.5">
          <div class="container">
            <div class="row align-items-center justify-content-center">

              <div class="col-md-12" data-aos="fade-up" data-aos-delay="400">

                <div class="row mb-4">
                  <div class="col-md-7">
                    <h1>Shop With Us</h1>
                    <p class="mb-5 lead">The biggest online bookstore</p>
                    <div>
                      <a href="{%url 'store:book'%}" class="btn btn-white btn-outline-white py-3 px-5 rounded-0 mb-lg-0 mb-2 d-block d-sm-inline-block">Shop Now</a>
                      <a href="{%url 'store:search'%}" class="btn btn-white py-3 px-5 rounded-0 d-block d-sm-inline-block">Search Books</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{%endblock content%}

project/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}